### ISSUE TITLE
Stephane Bortzmeyer: lying DNS resolvers

### ISSUE THREAD

**Issue by Abhayakara** [Abhayakara/draft-tldr-sutld-ps#86] opened 2017-06-12 14:42 UTC
> * Section 4.2.3 says "But it shares the problem that such names cannot
> be assumed either to be unique or to be functional in all contexts for
> all Internet-connected hosts." Unfortunately, because of the wide use
> of censorship through lying DNS resolvers, this problem is now part of
> our daily life. It would be nice if a name had the same global
> signification, but it is no longer true.

I believe this is out of scope and there is no action to take.

**Comment by wkumari** [comment] 2017-06-12 18:55
I agree, both that it would be nice if the world were different, and also that this is out of scope for this document.

**Comment by rdroms** [comment] 2017-06-12 19:56
I agree, as well, that the issue is out of scope.

**Comment by rdroms** [comment] 2017-06-23 21:06
Nothing to do.

**Closed as completed by rdroms** 2017-06-23 21:06 UTC
